---

- name: Provision a {{ project_name }} server
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: root
  vars_files:
    - vars/base.yml
    - vars/dev.yml

  roles:
    - base
    - db
    - web

