---

- name: Apache | Create folders for VHOSTS
  file: path={{ item }} state=directory
  with_items:
    - "{{ app_host_dir }}"
    - "{{ static_host_dir }}"
    - "{{ media_host_dir }}"

- name: Apache | Enable some required modules
  command: sudo a2enmod headers rewrite vhost_alias

- name: Apache | permissions for Media uploads
  command: sudo chgrp -R www-data {{ media_host_dir }}

- name: Apache | permissions for Media uploads
  command: sudo chmod -R g+w {{ media_host_dir }}

- name: Apache | Configuration file for our site
  action: template src=etc-apache2-sites-available-{{ item }}.j2 dest=/etc/apache2/sites-available/{{ item }}.conf
  with_items:
    - app
    - media
    - static

- name: Apache | Disable the default site
  action: command a2dissite 000-default.conf
  tags: common


- name: Apache | Enable our new site
  action:  command a2ensite {{ item }}
  with_items:
    - app
    - media
    - static
  notify: restart apache2