---

- name: Install required packages.
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - git
    - apache2
    - libapache2-mod-wsgi
    - python-pip
    - python-dev
    - python-setuptools
    - libjpeg-dev
    - libpq-dev
    - binutils
    - libproj-dev
    - gdal-bin
  tags: packages

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages
